DROP VIEW VBrDolaza_M
DROP VIEW VBrDolaza_Y
DROP VIEW VNarucP_M
DROP VIEW VNarucP_Y
DROP VIEW VPac_M
DROP VIEW VPac_Y
DROP VIEW ListZahvati_byDate
DROP VIEW ListPacjenti
DROP PROCEDURE ListLjecZah
DROP VIEW LjecnikoviZahvati
DROP PROCEDURE Det_Raspored
DROP VIEW Det_Raspored_View

DROP TABLE rac_zahvat
DROP TABLE racun
DROP TABLE zah_pac
DROP TABLE ljec_rasp
DROP TABLE ljec_zahvat
DROP TABLE zahvati
DROP TABLE ljec_pac
DROP TABLE ljecnik
DROP TABLE pacjent
DROP TABLE part
